# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 11:18
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('Top', 'TOP'), ('Jac', 'Jacket'), ('Dre', 'Dress'), ('Ski', 'Skirt'), ('Pan', 'Pants'), ('T-s', 'T-shirt'), ('Sui', 'Suits'), ('Bag', 'Bag'), ('Sho', 'Shoes'), ('Acc', 'Accessory')], max_length=3)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.FloatField()),
                ('detail', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductToTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SellerExtendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('C', 'Customer'), ('P', 'Product')], max_length=1)),
                ('id_num', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=100)),
                ('tel_no', models.CharField(max_length=45)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WaitForBillingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(max_length=45)),
                ('selected_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expire_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserExtendData')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product')),
            ],
        ),
        migrations.AddField(
            model_name='producttotag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Tag'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SellerExtendData'),
        ),
    ]
