# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 18:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('regisDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=45)),
                ('telNo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(max_length=45)),
                ('createDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.FloatField()),
                ('detail', models.CharField(max_length=500)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('regisDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('email', models.CharField(max_length=45)),
                ('address', models.CharField(max_length=100)),
                ('telNo', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Seller'),
        ),
    ]
