# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 08:12
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('type', models.CharField(choices=[('Top', 'top'), ('Jac', 'jacket'), ('Dre', 'dress'), ('Ski', 'skirt'), ('Pan', 'pants'), ('Sht', 'shorts'), ('T-s', 't-shirt'), ('Sui', 'suits'), ('Bag', 'bag'), ('Sho', 'shoes'), ('Acc', 'accessory')], max_length=3)),
                ('create_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('price', models.FloatField(default=0)),
                ('detail', models.CharField(max_length=500)),
                ('amount', models.IntegerField(default=1)),
                ('reserved', models.IntegerField(default=0)),
                ('sold', models.IntegerField(default=0)),
                ('view', models.IntegerField(default=0)),
                ('picture_path', models.ImageField(default='product_pic/product-minimize.jpg', upload_to='product_pic/')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_pic', models.ImageField(blank=True, upload_to='slip_pic/')),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('w', 'wait_for_check'), ('s', 'success'), ('f', 'fail')], default='w', max_length=1)),
                ('top_up_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopUp2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_pic', models.ImageField(blank=True, upload_to='slip_pic/')),
                ('price', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('w', 'wait_for_check'), ('s', 'success'), ('f', 'fail')], default='w', max_length=1)),
                ('top_up_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('wpy', 'wait_for_pay'), ('wac', 'wait_for_admin_confirm'), ('wss', 'wait_for_seller_sent'), ('suc', 'success'), ('cnp', 'customer_not_pay'), ('cpe', 'customer_pay_error'), ('ccl', 'customer_cancel'), ('sns', 'seller_not_sent_product')], default='wpy', max_length=3)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_date', models.DateTimeField(default=datetime.datetime(2017, 11, 9, 15, 12, 40, 37823))),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('payment_picture', models.ImageField(blank=True, upload_to='payment_pic/')),
                ('transport_code', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('wpy', 'wait_for_pay'), ('wac', 'wait_for_admin_confirm'), ('wss', 'wait_for_seller_sent'), ('suc', 'success'), ('cnp', 'customer_not_pay'), ('cpe', 'customer_pay_error'), ('ccl', 'customer_cancel'), ('sns', 'seller_not_sent_product')], default='suc', max_length=3)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('transport_code', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='UserExtendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_num', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=1000)),
                ('tel_no', models.CharField(max_length=45)),
                ('picture', models.ImageField(default='user_pic/icon.png', upload_to='user_pic/')),
                ('selling_expire_date', models.DateTimeField(default=datetime.datetime.now)),
                ('bank_account', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserExtendData'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserExtendData'),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Tag'),
        ),
    ]
