# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 14:47
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_pic', models.ImageField(blank=True, upload_to='slip_pic/')),
                ('top_up_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('wpy', 'wait_for_pay'), ('wac', 'wait_for_admin_confirm'), ('wss', 'wait_for_seller_sent'), ('wp1', 'wait_for_receive_product_1'), ('wp2', 'wait_for_receive_product_2'), ('suc', 'success'), ('cnp', 'customer_not_pay'), ('ccl', 'customer_cancel'), ('cnr', 'customer_not_receive_product'), ('sns', 'seller_not_sent_product')], default='wpy', max_length=3)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_picture', models.ImageField(blank=True, upload_to='payment_pic/')),
                ('transport_code', models.CharField(blank=True, max_length=13)),
                ('title_string', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='waitforbillingproduct',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='waitforbillingproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userextenddata',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='picture_path',
            field=models.ImageField(default='product_pic/catalog-minimize.jpg', upload_to='product_pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextenddata',
            name='picture',
            field=models.ImageField(default='product_pic/catalog-minimize.jpg', upload_to='user_pic/'),
        ),
        migrations.AddField(
            model_name='userextenddata',
            name='selling_expire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userextenddata',
            name='status',
            field=models.CharField(choices=[('n', 'can_not_sell'), ('c', 'can_sell')], default='n', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserExtendData'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Top', 'top'), ('Jac', 'jacket'), ('Dre', 'dress'), ('Ski', 'skirt'), ('Pan', 'pants'), ('Sht', 'shorts'), ('T-s', 't-shirt'), ('Sui', 'suits'), ('Bag', 'bag'), ('Sho', 'shoes'), ('Acc', 'accessory')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userextenddata',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='WaitForBillingProduct',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserExtendData'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
