# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-04 17:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerExtendData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='product',
            name='picture_path',
            field=models.ImageField(default=b'product_pic/catalog-minimize.jpg', upload_to=b'product_pic/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.SellerExtendData'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(b'Top', b'TOP'), (b'Jac', b'Jacket'), (b'Dre', b'Dress'), (b'Ski', b'Skirt'), (b'Pan', b'Pants'), (b'Sht', b'Shorts'), (b'T-s', b'T-shirt'), (b'Sui', b'Suits'), (b'Bag', b'Bag'), (b'Sho', b'Shoes'), (b'Acc', b'Accessory')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userextenddata',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='userextenddata',
            name='type',
            field=models.CharField(choices=[(b'C', b'Customer'), (b'S', b'Seller')], max_length=1),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
    ]
