# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-28 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userextenddata',
            name='type',
            field=models.CharField(choices=[('C', 'Customer'), ('S', 'Seller')], max_length=1),
        ),
    ]
