# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-09 15:55
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slip_pic', models.ImageField(blank=True, upload_to=b'slip_pic/')),
                ('top_up_date', models.DateTimeField(default=datetime.datetime.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[(b'wpy', b'wait_for_pay'), (b'wac', b'wait_for_admin_confirm'), (b'wss', b'wait_for_seller_sent'), (b'wp1', b'wait_for_receive_product_1'), (b'wp2', b'wait_for_receive_product_2'), (b'suc', b'success'), (b'cnp', b'customer_not_pay'), (b'ccl', b'customer_cancel'), (b'cnr', b'customer_not_receive_product'), (b'sns', b'seller_not_sent_product')], default=b'wpy', max_length=3)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('expire_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_picture', models.ImageField(blank=True, upload_to=b'payment_pic/')),
                ('transport_code', models.CharField(blank=True, max_length=13)),
                ('title_string', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.RemoveField(
            model_name='waitforbillingproduct',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='waitforbillingproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='userextenddata',
            name='type',
        ),
        migrations.AddField(
            model_name='product',
            name='picture_path',
            field=models.ImageField(default=b'product_pic/catalog-minimize.jpg', upload_to=b'product_pic/'),
        ),
        migrations.AddField(
            model_name='product',
            name='reserved',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userextenddata',
            name='picture',
            field=models.ImageField(default=b'product_pic/catalog-minimize.jpg', upload_to=b'user_pic/'),
        ),
        migrations.AddField(
            model_name='userextenddata',
            name='selling_expire_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='userextenddata',
            name='status',
            field=models.CharField(choices=[(b'n', b'can_not_sell'), (b'c', b'can_sell')], default=b'n', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserExtendData'),
        ),
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[(b'Top', b'top'), (b'Jac', b'jacket'), (b'Dre', b'dress'), (b'Ski', b'skirt'), (b'Pan', b'pants'), (b'Sht', b'shorts'), (b'T-s', b't-shirt'), (b'Sui', b'suits'), (b'Bag', b'bag'), (b'Sho', b'shoes'), (b'Acc', b'accessory')], max_length=3),
        ),
        migrations.AlterField(
            model_name='userextenddata',
            name='address',
            field=models.CharField(max_length=1000),
        ),
        migrations.DeleteModel(
            name='Seller',
        ),
        migrations.DeleteModel(
            name='WaitForBillingProduct',
        ),
        migrations.AddField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.UserExtendData'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Product'),
        ),
    ]
