# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-30 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='static/img/catalog-minimize.jpg', upload_to='product_pic/'),
        ),
    ]
