# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 08:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup2',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 9, 15, 14, 57, 175809)),
        ),
        migrations.DeleteModel(
            name='TopUp2',
        ),
    ]
