# -*- coding: utf-8 -*-
# Generated by Django 1.11b1 on 2017-11-19 18:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171120_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 23, 1, 17, 27, 782741)),
        ),
    ]
