# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 17:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171106_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextenddata',
            name='free_trial_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 0, 17, 28, 292106)),
        ),
    ]
