# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-15 17:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20171116_0017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='receive_date',
        ),
        migrations.RemoveField(
            model_name='transactionlog',
            name='receive_date',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 19, 0, 18, 9, 763462)),
        ),
    ]
