# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 13:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20171009_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('seller', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('amount', models.IntegerField(default=1)),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('wpy', 'wait_for_pay'), ('wac', 'wait_for_admin_confirm'), ('wss', 'wait_for_seller_sent'), ('wp1', 'wait_for_receive_product_1'), ('wp2', 'wait_for_receive_product_2'), ('suc', 'success'), ('cnp', 'customer_not_pay'), ('ccl', 'customer_cancel'), ('cnr', 'customer_not_receive_product'), ('sns', 'seller_not_sent_product')], default='suc', max_length=3)),
                ('create_date', models.DateTimeField(default=datetime.datetime.now)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(blank=True, null=True)),
                ('receive_date', models.DateTimeField(blank=True, null=True)),
                ('transport_code', models.CharField(blank=True, max_length=13)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='title_string',
        ),
        migrations.AddField(
            model_name='topup',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='transaction',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receive_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 12, 20, 23, 26, 423532)),
        ),
    ]
