# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 08:48
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171009_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topup',
            name='user',
        ),
        migrations.AlterField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, to='main.Tag'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 13, 15, 48, 10, 967878)),
        ),
        migrations.AlterField(
            model_name='userextenddata',
            name='picture',
            field=models.ImageField(default='user_pic/icon.png', upload_to='user_pic/'),
        ),
        migrations.DeleteModel(
            name='TopUp',
        ),
    ]
