# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-24 05:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20171116_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 27, 12, 39, 40, 360326)),
        ),
    ]
