# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 04:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171010_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 15, 11, 21, 54, 135981)),
        ),
    ]
