# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-19 10:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20171016_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture_path',
            field=models.ImageField(default='product_pic/product-minimize.jpg', upload_to='product_pic/'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='expire_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 22, 17, 26, 13, 698233)),
        ),
    ]
